# recode by damar
# source : https://github.com/Arya-Blitar22/
port: 7890
socks-port: 7891
mixed-port: 10809
mode: global
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret : ""
bind-address: "*"
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7894
  use-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - 1.1.1.1
  fallback:
    - https://dns.google/dns-query
#vmess   
proxies:
#vmess
  - name: vmess
    server: bug.com
    port: port
    type: vmess
    uuid: uuid
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: hostname
    network: ws
    ws-opts:
      path: /path/
      headers:
        Host: hostname
    udp: true
#vmessGrpc
  - name: vmessGrpc
    server: bug.com
    port: 443
    type: vmess
    uuid: uuid
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: hostname
    network: grpc
    grpc-opts:
      grpc-service-name: grpc
    udp: true
#Trojan-ssl
  - name: dmr
    server: 172.105.119.7
    port: 443
    type: trojan
    password: Damar
    skip-cert-verify: true
    sni: video.joox.com
    udp: true
  - name: idhw1
    server: id-rackhtj.bonds.id
    port: 443
    type: trojan
    password: a2eba940-e275-11ec-b717-1239d0255272
    skip-cert-verify: true
    sni: video.joox.com
    udp: true
  - name: unlihw1
    server: w21-trojan.bonds.id
    port: 443
    type: trojan
    password: caf4ce80-df59-11ec-8bd0-1239d0255272
    skip-cert-verify: true
    sni: video.joox.com
    udp: true
#trojango
  - name: trgo
    server: hostname
    port: 443
    type: trojan
    password: uuid
    skip-cert-verify: true
    sni: hostname
    network: ws
    ws-opts:
      path: /path
      headers:
        Host: hostname
#trojanGrpc
  - name: TrojanGrpc
    server: bug.com
    port: 8443
    type: trojan
    password: password
    skip-cert-verify: true
    sni: hostname
    network: grpc
    grpc-opts:
      grpc-service-name: xray-trojan-grpc
    udp: true
proxy-groups:
  - name: Damarr
    type: select
    proxies:
      - vmess
      - vmessGrpc
      - dmr
      - idhw1
      - unlihw1
      - Trojan-Ssl1
      - Trojan-Ssl2
      - trgo
      - TrojanGrpc
      - LOAD-BALANCE
      - BEST-PING
      - FALLBACK
      - DIRECT
  - name: LOAD-BALANCE
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - vmess
      - vmessGrpc
      - dmr
      - idhw1
      - unlihw1
      - Trojan-Ssl1
      - Trojan-Ssl2
      - trgo
      - TrojanGrpc
  - name: BEST-PING
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - vmess
      - vmessGrpc
      - dmr
      - idhw1
      - unlihw1
      - Trojan-Ssl1
      - Trojan-Ssl2
      - trgo
      - TrojanGrpc
  - name: FALLBACK
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - vmess
      - vmessGrpc
      - dmr
      - idhw1
      - unlihw1
      - Trojan-Ssl1
      - Trojan-Ssl2
      - trgo
      - TrojanGrpc
rule-providers:
  clash:
    type: http
    behavior: domain
    url: https://howdy.id/download/rules/clash.txt
    path: ./providers/rule-provider_clash.yaml
    interval: 86400
rules:
  - MATCH,Damarr
#Start Coy...
