# recode by damar
# source : https://github.com/Arya-Blitar22/
port: 7890
socks-port: 7891
mixed-port: 10809
mode: global
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret : ""
bind-address: "*"
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7894
  use-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - 1.1.1.1
  fallback:
    - https://dns.google/dns-query
#vmess   
proxies:
#Trojan-ssl
  - name: dmr
    server: 172.105.119.7
    port: 443
    type: trojan
    password: Damar
    skip-cert-verify: true
    sni: video.joox.com
    udp: true
  - name: idhw1
    server: id-rackhtj.bonds.id
    port: 443
    type: trojan
    password: a2eba940-e275-11ec-b717-1239d0255272
    skip-cert-verify: true
    sni: video.joox.com
    udp: true
  - name: unlihw1
    server: w21-trojan.bonds.id
    port: 443
    type: trojan
    password: caf4ce80-df59-11ec-8bd0-1239d0255272
    skip-cert-verify: true
    sni: video.joox.com
    udp: true
  - name: Trojan-Ssl1
    server: 103.93.59.208
    port: 443
    type: trojan
    password: 742f9630-d0bc-11ec-b8c1-1239d0255272
    skip-cert-verify: true
    sni: pubgmobile.com
    udp: true
  - name: Trojan-Ssl2
    server: 103.93.59.208
    port: 443
    type: trojan
    password: 742f9630-d0bc-11ec-b8c1-1239d0255272
    skip-cert-verify: true
    sni: pubgmobile.com
    udp: true
proxy-groups:
  - name: Damarr
    type: select
    proxies:
      - dmr
      - idhw1
      - unlihw1
      - Trojan-Ssl1
      - Trojan-Ssl2
      - LOAD-BALANCE
      - BEST-PING
      - FALLBACK
      - DIRECT
  - name: LOAD-BALANCE
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - dmr
      - idhw1
      - unlihw1
      - Trojan-Ssl1
      - Trojan-Ssl2
  - name: BEST-PING
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - dmr
      - idhw1
      - unlihw1
      - Trojan-Ssl1
      - Trojan-Ssl2
  - name: FALLBACK
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - dmr
      - idhw1
      - unlihw1
      - Trojan-Ssl1
      - Trojan-Ssl2
rule-providers:
  clash:
    type: http
    behavior: domain
    url: https://howdy.id/download/rules/clash.txt
    path: ./providers/rule-provider_clash.yaml
    interval: 86400
rules:
  - MATCH,Damarr
#Start Coy...
